/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

 #include <mysql/mysql.h>
#include <stdio.h>
#include "twitter.h"

MYSQL retornaConexao(){
	MYSQL conexao;
	mysql_init(&conexao);
	if (mysql_real_connect(&conexao, "localhost", "root", "root", "twitter", 0, NULL, 0) ){
		return conexao;
	}
}

int *
post_topic_1_svc(postTopic *argp, struct svc_req *rqstp)
{
	static int  result=1;
  int res;
  char *qry;
  qry = (char *)malloc(100*sizeof(char));
  sprintf(qry,"INSERT INTO post_topic(username,topic,post,time_post) values('%s','%s','%s',NOW());",argp->username,argp->topicName,argp->post);
  MYSQL conexao = retornaConexao();
  res = mysql_query(&conexao,qry);
  mysql_close(&conexao);
  free(qry);
  if(!res){
    printf("Usuário %s criou um post-topic\n",argp->username);
    return &result;
  }
  else{
    result=0;
    printf("ERRO\n");
    return &result;
  }
}

int *
follow_1_svc(followUser *argp, struct svc_req *rqstp)
{
	static int  result=1;
  int res,res2;
  MYSQL conexao = retornaConexao();
  char *qry,*qry2;
	qry = (char *)malloc(100*sizeof(char));
  qry2 = (char *)malloc(100*sizeof(char));
	sprintf(qry,"INSERT INTO following(username,following) values('%s','%s');",argp->username,argp->usernameFollow);
  sprintf(qry2,"INSERT INTO followers(username,follow) values('%s','%s');",argp->usernameFollow,argp->username);
  res = mysql_query(&conexao,qry);
  res2 = mysql_query(&conexao,qry2);
  free(qry);
  free(qry2);
	mysql_close(&conexao);
  if(res && res2){
    printf("Erro\n");
    result=0;
    return &result;
  }
  else{
    printf("Usuário %s seguiu %s\n",argp->username,argp->usernameFollow);
    return &result;
  }

}

char **
list_users_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	result = (char*)calloc(10000,sizeof(char));
	MYSQL_RES *resp;
  MYSQL_ROW linhas;
  MYSQL_FIELD *campos;
	MYSQL conexao = retornaConexao();
	int conta;
  char qry[]="SELECT * FROM usuario;";
		if(mysql_query(&conexao,qry)){
			printf("ERRO\n");
		}
		else{
			resp = mysql_store_result(&conexao);//recebe a consulta
			if (resp){ //se houver consulta
				while ((linhas=mysql_fetch_row(resp)) != NULL){
          for (conta=0;conta<mysql_num_fields(resp);conta++){
						sprintf(result,"%s%s\n",result,linhas[conta]);
					}
        }
			}
			mysql_free_result(resp);//limpa a variável do resultado: resp
		}

  printf("Listou usuários\n");
	mysql_close(&conexao);
  return &result;

}

int *
create_user_1_svc(user *argp, struct svc_req *rqstp)
{
	static int  result=1;
	int res;
	char *qry;
	qry = (char *)malloc(100*sizeof(char));
	sprintf(qry,"INSERT INTO usuario(username) values('%s');",argp->username);
	MYSQL conexao = retornaConexao();
	res = mysql_query(&conexao,qry);
	mysql_close(&conexao);
	free(qry);
	if(!res){
    printf("Criou usuário %s\n",argp->username);
    return &result;
  }
	else{
		result=0;
		printf("ERRO\n");
		return &result;
	}

}

char **
search_topics_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
  result = (char*)calloc(10000,sizeof(char));
	MYSQL_RES *resp;
  MYSQL_ROW linhas;
  MYSQL_FIELD *campos;
	MYSQL conexao = retornaConexao();
	int conta;
  char qry[]="SELECT name FROM topic;";
		if(mysql_query(&conexao,qry)){
			printf("ERRO\n");
		}
		else{
			resp = mysql_store_result(&conexao);//recebe a consulta
			if (resp){ //se houver consulta
				while ((linhas=mysql_fetch_row(resp)) != NULL){
          for (conta=0;conta<mysql_num_fields(resp);conta++){
						sprintf(result,"%s%s\n",result,linhas[conta]);
					}
            printf("\n");
        }
			}
			mysql_free_result(resp);//limpa a variável do resultado: resp
		}
    printf("Procurou tópicos\n");
	mysql_close(&conexao);
  return &result;
}

int *
new_topic_1_svc(topic *argp, struct svc_req *rqstp)
{
	static int  result=1;
  int res;
	char *qry;
	qry = (char *)malloc(100*sizeof(char));
	sprintf(qry,"INSERT INTO topic(name,username) values('%s','%s');",argp->topicName,argp->username);
	MYSQL conexao = retornaConexao();
	res = mysql_query(&conexao,qry);
	mysql_close(&conexao);
	free(qry);
	if(!res){
    printf("Usuário %s criou novo tópico\n",argp->username);
    return &result;
  }
	else{
		result=0;
		printf("ERRO\n");
		return &result;
	}

}

int *
unfollow_1_svc(unfollowUser *argp, struct svc_req *rqstp)
{
	static int  result=1;
  int res,res2;
  MYSQL conexao = retornaConexao();
  char *qry,*qry2;
	qry = (char *)malloc(100*sizeof(char));
  qry2 = (char *)malloc(100*sizeof(char));
	sprintf(qry,"DELETE from following where username = '%s' and following = '%s';",argp->username,argp->usernameUnfollow);
  sprintf(qry2,"DELETE from followers where username = '%s' and follow = '%s';",argp->usernameUnfollow,argp->username);
  res = mysql_query(&conexao,qry);
  res2 = mysql_query(&conexao,qry2);
  free(qry);
  free(qry2);
	mysql_close(&conexao);
  if(res && res2){
    printf("Erro\n");
    result=0;
    return &result;
  }
  else{
    printf("Deixou de seguir\n");
    return &result;
  }

	/*
	 * insert server code here
	 */

	return &result;
}

char **
retrieve_topic_1_svc(topicTime *argp, struct svc_req *rqstp)
{
	static char * result;
  result = (char*)calloc(10000,sizeof(char));
  MYSQL_RES *resp;
  MYSQL_ROW linhas;
  MYSQL_FIELD *campos;
  MYSQL conexao = retornaConexao();
  int conta;
  char *qry;
  qry = (char *)malloc(100*sizeof(char));
  sprintf(qry,"SELECT post FROM post_topic where time_post > '%s';",argp->timestamp);
    if(mysql_query(&conexao,qry)){
      printf("ERRO\n");
    }
    else{
      resp = mysql_store_result(&conexao);//recebe a consulta
      if (resp){ //se houver consulta
        while ((linhas=mysql_fetch_row(resp)) != NULL){
          for (conta=0;conta<mysql_num_fields(resp);conta++){
            sprintf(result,"%s%s\n",result,linhas[conta]);
          }
        }
        // printf("Foi buscado um determinado post em um tópico \n");
      }

      mysql_free_result(resp);//limpa a variável do resultado: resp
    }
    
  mysql_close(&conexao);
  return &result;
}

int *
tweet_1_svc(tweetPost *argp, struct svc_req *rqstp)
{
	static int  result=1;
  int res;
	char *qry;
	qry = (char *)malloc(100*sizeof(char));
	sprintf(qry,"INSERT INTO twitte(username,post) values('%s','%s');",argp->username,argp->post);
	MYSQL conexao = retornaConexao();
	res = mysql_query(&conexao,qry);
	mysql_close(&conexao);
	free(qry);
	if(!res){
    printf("Usuário %s acabou de twittar\n",argp->username);
    return &result;
  }
	else{
		result=0;
		printf("ERRO\n");
		return &result;
	}

}
