/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "twitter.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
twitter_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		postTopic post_topic_1_arg;
		followUser follow_1_arg;
		user create_user_1_arg;
		topic new_topic_1_arg;
		unfollowUser unfollow_1_arg;
		topicTime retrieve_topic_1_arg;
		post twitte_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case POST_TOPIC:
		_xdr_argument = (xdrproc_t) xdr_postTopic;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) post_topic_1_svc;
		break;

	case FOLLOW:
		_xdr_argument = (xdrproc_t) xdr_followUser;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) follow_1_svc;
		break;

	case LIST_USERS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) list_users_1_svc;
		break;

	case CREATE_USER:
		_xdr_argument = (xdrproc_t) xdr_user;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) create_user_1_svc;
		break;

	case SEARCH_TOPICS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) search_topics_1_svc;
		break;

	case NEW_TOPIC:
		_xdr_argument = (xdrproc_t) xdr_topic;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) new_topic_1_svc;
		break;

	case UNFOLLOW:
		_xdr_argument = (xdrproc_t) xdr_unfollowUser;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) unfollow_1_svc;
		break;

	case RETRIEVE_TOPIC:
		_xdr_argument = (xdrproc_t) xdr_topicTime;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) retrieve_topic_1_svc;
		break;

	case TWITTE:
		_xdr_argument = (xdrproc_t) xdr_post;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) twitte_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (TWITTER_PROG, TWITTER_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, TWITTER_PROG, TWITTER_VERSION, twitter_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TWITTER_PROG, TWITTER_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, TWITTER_PROG, TWITTER_VERSION, twitter_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TWITTER_PROG, TWITTER_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
