/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "twitter.h"

bool_t
xdr_postTopic (XDR *xdrs, postTopic *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->topic, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->text, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_followUser (XDR *xdrs, followUser *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->usernameFollow, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user (XDR *xdrs, user *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_topic (XDR *xdrs, topic *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->topic, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_unfollowUser (XDR *xdrs, unfollowUser *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->usernameUnfollow, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_topicTime (XDR *xdrs, topicTime *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->topic, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->timestamp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_post (XDR *xdrs, post *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->text, ~0))
		 return FALSE;
	return TRUE;
}
