/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <string.h>
#include "twitter.h"


void
twitter_prog_1(char *host)
{
	CLIENT *clnt;
	postTopic  post_topic_1_arg;
	followUser  follow_1_arg;
	user  create_user_1_arg;
	topic  new_topic_1_arg;
	unfollowUser  unfollow_1_arg;
	topicTime  retrieve_topic_1_arg;
	post  twitte_1_arg;
	int  *result_1;
	int  *result_2;
	char **result_3;
	int  *result_4;
	char **result_5;
	int  *result_6;
	int  *result_7;
	char **result_8;
	int  *result_9;
	char *list_users_1_arg;
	char *search_topics_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TWITTER_PROG, TWITTER_VERSION, "udp");

	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = post_topic_1(&post_topic_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	result_2 = follow_1(&follow_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	result_3 = list_users_1((void*)&list_users_1_arg, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

	result_4 = create_user_1(&create_user_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	result_5 = search_topics_1((void*)&search_topics_1_arg, clnt);
	if (result_5 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

	result_6 = new_topic_1(&new_topic_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	result_7 = unfollow_1(&unfollow_1_arg, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	result_8 = retrieve_topic_1(&retrieve_topic_1_arg, clnt);
	if (result_8 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

	result_9 = twitte_1(&twitte_1_arg, clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void create_user(CLIENT *clnt);
int main (int argc, char *argv[]) {
	CLIENT *clnt;
	char *host;
	int opt;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	clnt = clnt_create(host, TWITTER_PROG, TWITTER_VERSION, "udp");

	/* Verifica se a referência foi criada */
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	while(1) {
		printf("\n##################################################################");
		printf("\n############################## MENU ##############################");
		printf("\n##################################################################");
	
		printf("\n\nDigite:");
		printf("\n0 - Encerrar");
		printf("\n1 - Criar Usuário");
		printf("\n2 - Listar Usuários");
		printf("\n3 - Seguir");
		printf("\n4 - Deixar de Seguir");
		printf("\n5 - Twittar");
		printf("\n6 - Criar Novo Tópico");
		printf("\n7 - Listar Tópicos");
		printf("\n8 - Postar Tópico");
		printf("\n9 - Recuperar Tópicos\n\n");

		scanf("%d", &opt);

		switch(opt) {
			case 0:
				exit(0);

			case 1:
				create_user(clnt);
				break;
				
			case 2:
				break;

			case 3:
				break;

			case 4:
				break;

			case 5:
				break;

			case 6:
				break;

			case 7:
				break;

			case 8:
				break;

			case 9:
				break;

			default:
				printf("\n\nOpção Inválida!\n");
				break;
		}
	}
	
	exit(0);
}

void create_user(CLIENT *clnt) {
	user usuario;
	char username[3];
	int *result;

	// username = (char *) malloc(5*sizeof(char));
	printf("Digite o nome  do usuário a ser criado:\n");
	scanf("%s", username);
	// username[2] = '\0';

	printf("\nUSERNAME: %s ---- %ld", username, strlen(username));

	usuario.username = username;
	// usuario.username = (char *) malloc((int) strlen(username+1)*sizeof(char));
	// strcpy(usuario.username, username);

	// printf("\n\nUSER: %s\n\n", usuario.username);

	result = create_user_1(&usuario, clnt);
}